### ISSUE TITLE
Test for sumBelow has incorrect text

### ISSUE THREAD

**Issue by TwoFistedJustice** [JS-Challenges/recursion-prompts#59]
part1.js line 279 

it says "should return the sum of an array of negative integers"

This function tests integers, not arrays. The tests in question pass negative integers as arguments.

The wording from the immediate previous test could probably be adapted.

**Comment by mybrainishuge** [comment]
Nice catch, @TwoFistedJustice. A lot of these tests started by copying other tests and modifying them. I clearly overlooked this one. Would you like to make a PR to correct this?

**Comment by TwoFistedJustice** [comment]
Sure! 

But you've only got one branch and I don't want to muck up your Master so I added a branch on my fork called "proof-read". 

I believe you would have to have a fork of the same name yes?

**Comment by mybrainishuge** [comment]
I could handle this myself, but I like to give other people the opportunity to contribute. You can make a temporary clone of the main repo to make your changes so you don't disturb your personal work.
```
$ git clone https://github.com/JS-Challenges/recursion-prompts.git
$ cd recursion-prompts
$ git checkout -b new_branch_name_of_your_choice
```
Make changes to the wording issue you found. I suggest something like "should return the sum of negative integers above given negative integer"
```
$ git add --all
$ git commit -m "your relevant commit message here"
$ git push origin your_branch_name
```
Open https://github.com/JS-Challenges/recursion-prompts in your web browser and create a new pull request against master. Add me as a reviewer. Let me know if you run into any issues with these steps. Once it's merged in, you can trash the temporary local clone. @TwoFistedJustice

**Comment by TwoFistedJustice** [comment]
I can't push my change. I get:

ERROR: Permission to JS-Challenges/recursion-prompts.git denied to TwoFistedJustice.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mybrainishuge** [comment]
I think I had a restriction enabled preventing pushing. Try again. @TwoFistedJustice

**Comment by mybrainishuge** [comment]
I added you as a collaborator on the main repo. I don't have ownership of your fork.

**Comment by mybrainishuge** [comment]
Every person who has contributed to this repo has done it by pushing to their own fork and submitting a PR from their fork against this repo as their base. It's been a while since I setup this repo and didn't quite remember the settings.

**Comment by TwoFistedJustice** [comment]
I *think* I made a pull request from my local fork... first time. So not really sure if I did it right.

**Comment by mybrainishuge** [comment]
Approved and merged. You've successfully contributed to an open source project. Thanks, @TwoFistedJustice!

**Comment by TwoFistedJustice** [comment]
Achievement unlocked!
