### ISSUE TITLE
Test for recursion on 15.  Compare Strings uses strings of unequal length

### ISSUE THREAD

**Issue by TwoFistedJustice** [JS-Challenges/recursion-prompts#60]
Line 890 of part1.js
Problem 15 compare strings
It uses strings of unequal length 'house' and 'houses' to check that recursive calls equal at least 1.

This is a problem because the first thing many people will do is compare string length. Which is a good habit it to be in.

if the strings compared were 'house' and 'houes'  it would test for recursion calls as well as pass a test for equal length. (or even just 'house' and 'house')

Actual:
```
it('should use recursion by calling self', function() {
        compareStr('house', 'houses');  <<-----------------------
        expect(compareStr.callCount).to.be.above(1);
      });
```

suggested:
        compareStr('house', 'houes');

**Comment by mybrainishuge** [comment]
@TwoFistedJustice Do you plan on submitting a PR for this as well?

**Comment by mybrainishuge** [comment]
@TwoFistedJustice I'm going to close this issue. If you would like to make a PR with the changes you suggested, reopen the issue and ping me. I'll be happy to review it.
