### ISSUE TITLE
Prompt #34 - Minimize Zeroes - needs more robust testing

### ISSUE THREAD

**Issue by seanmcnamara33** [JS-Challenges/recursion-prompts#90]
Tests should be run against an array which also has multiple consecutive digits other than zero in a row. 

With the following code, the current automated mocha tests  will pass:

var minimizeZeroes = function(array) {
  if (array.length <= 1) {
    return array;
  } else if (array[0] !== array[1]) {
    return [array[0]].concat(minimizeZeroes(array.slice(1)));
  } else {
    return minimizeZeroes(array.slice(1));
  }
};

But the above code also minimizes numbers other than zero as well

The following function call :
minimizeZeroes([1, 2, 2, 2, 3, 0, 0, 4, 0, 0])
will produce:
[1, 2, 3, 0, 4, 0]
when it should produce:
[1, 2, 2, 2, 3, 0, 4, 0]

Suggestion for fix:
add multiple consecutive digits which aren't zero to the test

**Comment by mybrainishuge** [comment]
@seanmcnamara33 Feel free to open a PR with your suggested changes and assign it to me.

**Comment by mybrainishuge** [comment]
The purpose of this repo is to provide exercises for practicing recursion which I think it does reasonably well. I focus on whether tests account for enforcing recursion and try not to get lost in all the possible edge cases that don't necessarily pertain to recursion itself. However, if other members of the community want to expand tests or other aspects of the repo, I welcome those additions.

Closing this issue, but feel free to contribute the suggested change if you find it valuable.
