### ISSUE TITLE
[Suggestion] Improve the test spec for the range problem

### ISSUE THREAD

**Issue by aileks** [JS-Challenges/recursion-prompts#95]
I believe the test spec for the range problem is flawed. It expects you to include the last number but not the first number within a range. However, ranges don't typically operate like that and the edge cases you have to account for in this problem feel unnatural or incorrect. A classic range problem could be solved recursively like so:
```js
function range(start, end) {
  if (start > end) return [start].concat(range(start - 1, end));
  if (start === end) return [];
  return [start].concat(range(start + 1 , end));
}
```

But because of the weird exclusivity of the test spec (and the lack of a description if I'm being honest) this fails despite doing what you'd expect in any other scenario.

**Comment by mybrainishuge** [comment]
Thanks for taking time to work through the repo and provide feedback. It means a lot to know people find this useful and care enough to offer feedback. Now on to my response...

> It expects you to include the last number but not the first number within a range.

Where are you seeing that the end input should be inclusive? The [comment](https://github.com/JS-Challenges/recursion-prompts/blob/master/src/recursion.js#L35) accompanying the prompt indicates both start and end inputs are exclusive:
```
// 6. Get the integers within a range (x, y).
// range(2,9); // [3,4,5,6,7,8]
```
None of the [tests](https://github.com/JS-Challenges/recursion-prompts/blob/master/spec/part1.js#L316-L371) expect either start or end inputs to be inclusive. In fact, one test is titled `should return the integers between two numbers`. What could I have done to make this clearer?

This repo is a resource intended to aid individuals in practicing recursion. Function names are intended to convey something about the function's purpose, but it shouldn't be assumed that any are replicas of external resources. Many of these functions are inspired by methods native to JavaScript or utils from external libraries like `lodash`, but several are somewhat silly with no practical purpose other than to practice recursion.

Part of getting comfortable with recursion is considering the gotchas and pitfalls inherent to recursion. When given specific parameters, how do you handle the edge cases those parameters create? You determine how to handle them within the confines of recursion. Whether they feel natural is no direct indication of correctness.

There's one fundamental question we should ask: `Does this function help me practice recursion?`

If the answer is yes, then our objective is accomplished. The intent is not to match any single external resource, but to provide a means for practicing recursion. If a test is objectively wrong (e.g., `1 + 1 = 3`), then that needs to be remedied, but I'm not aware of an incorrect test in this case.

I hope this answers your question. I recognize that whether something "feels natural" is a completely valid response to a thing. Sometimes a thing feels unnatural for valid reasons and needs to be redesigned. Other times, there are valid reasons for something to feel unnatural. Let me know if I can offer additional clarity or if I've missed something in your concern. And again, I really appreciate your feedback.

**Comment by aileks** [comment]
> Where are you seeing that the end input should be inclusive? The [comment](https://github.com/JS-Challenges/recursion-prompts/blob/master/src/recursion.js#L35) accompanying the prompt indicates both start and end inputs are exclusive:

Sorry, I mispoke (mistyped?). It was early when I typed this out. I meant to say it's exclusive of both the start and end, which is atypical. Built-in methods within JavaScript that deal with ranges are only exclusive of the end (i.e. slice, substring), thus the comments about feeling natural and meeting expectations. The same goes for some JS libraries that have range functions or functions that involve ranges (lodash comes to mind). I could also go on about ranges within math and how most programming languages follow half open intervals, etc. I do genuinely believe that test spec for this particular problem is flawed - whether you're testing an iterative version or a recursive version.

**Comment by mybrainishuge** [comment]
I could've named these functions random words and the repo would serve the same purpose. The fact that this function happens to be named `range` isn't important because an example and tests for what's expected are provided. The concern of this repo is to offer a means to practice recursion and encounter the challenges therein, not to match the behavior of functions similarly named elsewhere.

Take a look at other functions in this repo. Why does `sum` take an array? Wouldn't most people expect `sum` to take two or more numbers? Some people start the fibonacci sequence at 1 and 1 and others start it at 1 and 2, but it starts at 0 and 1 here. Why? 🤷‍♂️ Doesn't matter because the purpose is recursion.

If you've come to this repo to find ubiquitous functions to incorporate into your repertoire, you'll be sorely disappointed. However, if you've come here to practice recursion, we have something for you.
