### ISSUE TITLE
Floating Point Division

### ISSUE THREAD

**Issue by aileks** [JS-Challenges/recursion-prompts#96]
(I forgot to report this when going through through the problems and it just occurred to me.)

The test spec doesn't account for the quirk behind floating point division for the compute exponent problem.
![image](https://github.com/JS-Challenges/recursion-prompts/assets/88669313/ad660d27-223d-4d2c-bdbd-aea63fe185f2)

This isn't an edge case to account for but rather the specification for floating point division by IEE. The relevant specification is [IEE-754](https://standards.ieee.org/ieee/754/6210/).

**Comment by mybrainishuge** [comment]
How would making this change aid you in practicing recursion?

**Comment by aileks** [comment]
Because the result of the division within the test case is expected? I don't see the point in your question. Flawed test specs hinder learning in general.

**Comment by mybrainishuge** [comment]
How would you implement this so the test would pass as you expect?

**Comment by mybrainishuge** [comment]
My question was sincere. If I can understand what about the implementation will aid in practicing recursion, I'm more than willing to update the test accordingly. Understanding how you would implement this would provide valuable insight that will help me know how to improve this. It's clear that you have a passion for improving your environment which I greatly respect and I want to figure out a way that we can do that that satisfies both of our goals.
